import React from "react";
import { Composition, staticFile } from "remotion";
import { LongformComposition } from "@/compositions/LongformComposition";
import { SynthesizedPreview } from "@/compositions/SynthesizedPreview";
import type { SynthesizedPreviewProps } from "@/compositions/SynthesizedPreview";
import { buildCompositionProps } from "@/pipeline/buildProps";
import type { CompositionProps } from "@/pipeline/buildProps";
import testBook from "../content/books/test-book.json";
import miracleMorningBook from "../content/books/miracle-morning.json";
import atomicHabitsBook from "../content/books/atomic-habits.json";
import millionaireFastlaneBook from "../content/books/millionaire-fastlane.json";
import crazyOneYearBook from "../content/books/crazy-one-year.json";
import storyBrandBook from "../content/books/story-brand-2025.json";
import type { BookContent } from "@/types";
import { loadProjectFonts } from "@/design/fonts/loadFonts";
import { useTheme } from "@/design/themes/useTheme";
import { synthesizeGaps } from "@/planner/sceneSynthesizer";
import type { SynthesizerContext } from "@/planner/sceneSynthesizer";
import {
  miracleMorningGaps,
  miracleMorningFingerprint,
} from "@/planner/__tests__/miracleMorning.fixture";
import hookBlueprint from "../generated/books/atomic-habits-2024/06-blueprints/hook-01.blueprint.json";
import frameworkBlueprint from "../generated/books/atomic-habits-2024/06-blueprints/framework-01.blueprint.json";
import type { SceneBlueprint } from "@/types";

loadProjectFonts();

/**
 * Reads TTS manifest + planning data at render time.
 * Planning data comes from assets/planning/{bookId}.plan.json
 * (generated by scripts/prepare-plan.ts before render).
 */
async function calculateMetadataFromManifest({
  defaultProps,
}: {
  defaultProps: CompositionProps;
}) {
  let scenes = defaultProps.scenes;
  let theme = defaultProps.theme;

  // --- Phase 1: Load planning data (theme + blueprints) ---
  try {
    const planRes = await fetch(
      staticFile(`planning/${defaultProps.bookId}.plan.json`),
    );
    const planData = await planRes.json();
    if (planData.hasPlan) {
      // Apply theme overrides
      theme = planData.theme;
      // Attach _blueprint to relevant scenes
      const bpMap: Record<string, unknown> = planData.blueprintScenes ?? {};
      scenes = scenes.map((scene) => {
        const bp = bpMap[scene.id];
        if (bp) {
          console.log(`[planning] ${scene.id} → BlueprintRenderer`);
          return { ...scene, _blueprint: bp };
        }
        return scene;
      });
      const bpCount = Object.keys(bpMap).length;
      const presetCount = scenes.length - bpCount;
      console.log(
        `[planning] ${defaultProps.bookId}: ${bpCount} blueprint, ${presetCount} preset, theme override applied`,
      );
    }
  } catch {
    // No planning data — use defaults (this is normal for books without planning)
  }

  // --- Phase 2: TTS manifest (duration resolution) ---
  try {
    const res = await fetch(staticFile("tts/manifest.json"));
    const manifest: { sceneId: string; durationFrames: number }[] =
      await res.json();
    const manifestMap = new Map(manifest.map((e) => [e.sceneId, e]));

    let cumulativeFrom = 0;
    const updatedScenes = scenes.map((scene) => {
      const entry = manifestMap.get(scene.id);
      const resolvedDuration = entry
        ? entry.durationFrames + 15 // TAIL_PADDING_FRAMES
        : scene.resolvedDuration;
      const from = cumulativeFrom;
      cumulativeFrom += resolvedDuration;
      return { ...scene, from, resolvedDuration };
    });

    const totalFrames = cumulativeFrom;
    if (totalFrames > 0) {
      return {
        durationInFrames: totalFrames,
        fps: defaultProps.fps,
        width: defaultProps.width,
        height: defaultProps.height,
        props: {
          ...defaultProps,
          scenes: updatedScenes,
          theme,
          totalDurationFrames: totalFrames,
        },
      };
    }
  } catch {
    // No manifest — use static defaults
  }
  return {
    durationInFrames: defaultProps.totalDurationFrames,
    fps: defaultProps.fps,
    width: defaultProps.width,
    height: defaultProps.height,
    props: { ...defaultProps, scenes, theme },
  };
}

const book = testBook as unknown as BookContent;
const mmBook = miracleMorningBook as unknown as BookContent;

// Build default props for preview (no TTS in preview mode)
const longformProps: CompositionProps = buildCompositionProps(book, "longform");
const shortsProps: CompositionProps = buildCompositionProps(book, "shorts");

// Miracle Morning — TTS audio + captions loaded at render time via manifest
const mmLongformProps: CompositionProps = buildCompositionProps(
  mmBook,
  "longform",
);

// Atomic Habits — 5min longform
const ahBook = atomicHabitsBook as unknown as BookContent;
const ahLongformProps: CompositionProps = buildCompositionProps(
  ahBook,
  "longform",
);

// Millionaire Fastlane — 5min longform
const mfBook = millionaireFastlaneBook as unknown as BookContent;
const mfLongformProps: CompositionProps = buildCompositionProps(
  mfBook,
  "longform",
);

// Crazy One Year — 7min longform
const coyBook = crazyOneYearBook as unknown as BookContent;
const coyLongformProps: CompositionProps = buildCompositionProps(
  coyBook,
  "longform",
);

// Story Brand — 6.5min longform
const sbBook = storyBrandBook as unknown as BookContent;
const sbLongformProps: CompositionProps = buildCompositionProps(
  sbBook,
  "longform",
);

// Build synthesized scene preview props
const synthTheme = useTheme("dark", "selfHelp");
const synthCtx: SynthesizerContext = {
  format: "longform",
  theme: synthTheme,
  from: 0,
  durationFrames: 180,
  narrationText: "",
  emotionalTones: miracleMorningFingerprint.emotionalTone,
};
const synthBlueprints = synthesizeGaps(miracleMorningGaps, synthCtx);
// Assign sequential `from` values
let synthFrom = 0;
for (const bp of synthBlueprints) {
  (bp as { from: number }).from = synthFrom;
  synthFrom += bp.durationFrames;
}
const synthProps: SynthesizedPreviewProps = {
  blueprints: synthBlueprints,
  totalDurationFrames: synthFrom,
  fps: 30,
  width: 1920,
  height: 1080,
};

// Blueprint v2 preview: hook-01 + framework-01 side by side
const blueprintV2: SceneBlueprint[] = [
  hookBlueprint as unknown as SceneBlueprint,
  {
    ...(frameworkBlueprint as unknown as SceneBlueprint),
    from: (hookBlueprint as any).durationFrames,
  },
];
const blueprintV2Props: SynthesizedPreviewProps = {
  blueprints: blueprintV2 as any,
  totalDurationFrames:
    (hookBlueprint as any).durationFrames +
    (frameworkBlueprint as any).durationFrames,
  fps: 30,
  width: 1920,
  height: 1080,
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="LongformComposition"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={LongformComposition as any}
        durationInFrames={longformProps.totalDurationFrames}
        fps={longformProps.fps}
        width={longformProps.width}
        height={longformProps.height}
        defaultProps={longformProps as any}
      />
      <Composition
        id="ShortsPreview"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={LongformComposition as any}
        durationInFrames={shortsProps.totalDurationFrames}
        fps={shortsProps.fps}
        width={shortsProps.width}
        height={shortsProps.height}
        defaultProps={shortsProps as any}
      />
      <Composition
        id="MiracleMorning"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={LongformComposition as any}
        durationInFrames={mmLongformProps.totalDurationFrames}
        fps={mmLongformProps.fps}
        width={mmLongformProps.width}
        height={mmLongformProps.height}
        defaultProps={mmLongformProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="AtomicHabits"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={LongformComposition as any}
        durationInFrames={ahLongformProps.totalDurationFrames}
        fps={ahLongformProps.fps}
        width={ahLongformProps.width}
        height={ahLongformProps.height}
        defaultProps={ahLongformProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="MillionaireFastlane"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={LongformComposition as any}
        durationInFrames={mfLongformProps.totalDurationFrames}
        fps={mfLongformProps.fps}
        width={mfLongformProps.width}
        height={mfLongformProps.height}
        defaultProps={mfLongformProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="CrazyOneYear"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={LongformComposition as any}
        durationInFrames={coyLongformProps.totalDurationFrames}
        fps={coyLongformProps.fps}
        width={coyLongformProps.width}
        height={coyLongformProps.height}
        defaultProps={coyLongformProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="StoryBrand"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={LongformComposition as any}
        durationInFrames={sbLongformProps.totalDurationFrames}
        fps={sbLongformProps.fps}
        width={sbLongformProps.width}
        height={sbLongformProps.height}
        defaultProps={sbLongformProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="SynthesizedPreview"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={SynthesizedPreview as any}
        durationInFrames={synthProps.totalDurationFrames}
        fps={synthProps.fps}
        width={synthProps.width}
        height={synthProps.height}
        defaultProps={synthProps as any}
      />
      <Composition
        id="BlueprintV2Preview"
        component={SynthesizedPreview as any}
        durationInFrames={blueprintV2Props.totalDurationFrames}
        fps={blueprintV2Props.fps}
        width={blueprintV2Props.width}
        height={blueprintV2Props.height}
        defaultProps={blueprintV2Props as any}
      />
    </>
  );
};
