import React from "react";
import { Composition, staticFile } from "remotion";
import { LongformComposition } from "@/compositions/LongformComposition";
import { SynthesizedPreview } from "@/compositions/SynthesizedPreview";
import type { SynthesizedPreviewProps } from "@/compositions/SynthesizedPreview";
import { buildCompositionProps } from "@/pipeline/buildProps";
import type { CompositionProps } from "@/pipeline/buildProps";
import testBook from "../content/books/test-book.json";
// --- AUTO-GENERATED IMPORTS START ---
import atomicHabitsBook from "../content/books/atomic-habits.json";
import brainSuccess2025Book from "../content/books/brain-success-2025.json";
import crazyOneYearBook from "../content/books/crazy-one-year.json";
import linchpin2025Book from "../content/books/linchpin-2025.json";
import millionaireFastlaneBook from "../content/books/millionaire-fastlane.json";
import miracleMorningBook from "../content/books/miracle-morning.json";
import nightCompass2025Book from "../content/books/night-compass-2025.json";
import richDadPoorDadBook from "../content/books/rich-dad-poor-dad.json";
import startupDesignerBook from "../content/books/startup-designer.json";
import storyBrand2025Book from "../content/books/story-brand-2025.json";
import toolsOfTitans2025Book from "../content/books/tools-of-titans-2025.json";
// --- AUTO-GENERATED IMPORTS END ---
import type { BookContent } from "@/types";
import { loadProjectFonts } from "@/design/fonts/loadFonts";
import { useTheme } from "@/design/themes/useTheme";
import { synthesizeGaps } from "@/planner/sceneSynthesizer";
import type { SynthesizerContext } from "@/planner/sceneSynthesizer";
import {
  miracleMorningGaps,
  miracleMorningFingerprint,
} from "@/planner/__tests__/miracleMorning.fixture";
import hookBlueprint from "../generated/books/atomic-habits-2024/06-blueprints/hook-01.blueprint.json";
import frameworkBlueprint from "../generated/books/atomic-habits-2024/06-blueprints/framework-01.blueprint.json";
import type { SceneBlueprint } from "@/types";

loadProjectFonts();

/**
 * Reads TTS manifest + planning data at render time.
 * Planning data comes from assets/planning/{bookId}.plan.json
 * (generated by scripts/prepare-plan.ts before render).
 */
async function calculateMetadataFromManifest({
  defaultProps,
}: {
  defaultProps: CompositionProps;
}) {
  let scenes = defaultProps.scenes;
  let theme = defaultProps.theme;

  // --- Phase 1: Load planning data (theme + blueprints + storyboard + art direction) ---
  let textureMood: string | undefined;
  try {
    const planRes = await fetch(
      staticFile(`planning/${defaultProps.bookId}.plan.json`),
    );
    const planData = await planRes.json();
    if (planData.hasPlan) {
      // Apply theme overrides
      theme = planData.theme;
      // Apply art direction
      textureMood = planData.textureMood;
      // Attach _blueprint and _storyboard to relevant scenes
      const bpMap: Record<string, unknown> = planData.blueprintScenes ?? {};
      const sbMap: Record<string, unknown> = planData.storyboardScenes ?? {};
      scenes = scenes.map((scene) => {
        const bp = bpMap[scene.id];
        const sb = sbMap[scene.id];
        const extensions: Record<string, unknown> = {};
        if (bp) {
          console.log(`[planning] ${scene.id} → BlueprintRenderer`);
          extensions._blueprint = bp;
        }
        if (sb) {
          extensions._storyboard = sb;
        }
        return Object.keys(extensions).length > 0
          ? { ...scene, ...extensions }
          : scene;
      });
      const bpCount = Object.keys(bpMap).length;
      const sbCount = Object.keys(sbMap).length;
      const presetCount = scenes.length - bpCount;
      console.log(
        `[planning] ${defaultProps.bookId}: ${bpCount} blueprint, ${presetCount} preset, ${sbCount} storyboard, textureMood=${textureMood ?? "none"}`,
      );
    }
  } catch {
    // No planning data — use defaults (this is normal for books without planning)
  }

  // --- Phase 2: TTS manifest (duration resolution) ---
  try {
    const res = await fetch(staticFile("tts/manifest.json"));
    const manifest: { sceneId: string; durationFrames: number }[] =
      await res.json();
    const manifestMap = new Map(manifest.map((e) => [e.sceneId, e]));

    let cumulativeFrom = 0;
    const updatedScenes = scenes.map((scene) => {
      const entry = manifestMap.get(scene.id);
      const resolvedDuration = entry
        ? entry.durationFrames + 15 // TAIL_PADDING_FRAMES
        : scene.resolvedDuration;
      const from = cumulativeFrom;
      cumulativeFrom += resolvedDuration;
      return { ...scene, from, resolvedDuration };
    });

    const totalFrames = cumulativeFrom;
    if (totalFrames > 0) {
      return {
        durationInFrames: totalFrames,
        fps: defaultProps.fps,
        width: defaultProps.width,
        height: defaultProps.height,
        props: {
          ...defaultProps,
          scenes: updatedScenes,
          theme,
          textureMood,
          totalDurationFrames: totalFrames,
        },
      };
    }
  } catch {
    // No manifest — use static defaults
  }
  return {
    durationInFrames: defaultProps.totalDurationFrames,
    fps: defaultProps.fps,
    width: defaultProps.width,
    height: defaultProps.height,
    props: { ...defaultProps, scenes, theme, textureMood },
  };
}

const book = testBook as unknown as BookContent;

// Build default props for preview (no TTS in preview mode)
const longformProps: CompositionProps = buildCompositionProps(book, "longform");
const shortsProps: CompositionProps = buildCompositionProps(book, "shorts");

// --- AUTO-GENERATED BOOKS START ---
const atomicHabitsProps: CompositionProps = buildCompositionProps(
  atomicHabitsBook as unknown as BookContent,
  "longform",
);
const brainSuccess2025Props: CompositionProps = buildCompositionProps(
  brainSuccess2025Book as unknown as BookContent,
  "longform",
);
const crazyOneYearProps: CompositionProps = buildCompositionProps(
  crazyOneYearBook as unknown as BookContent,
  "longform",
);
const linchpin2025Props: CompositionProps = buildCompositionProps(
  linchpin2025Book as unknown as BookContent,
  "longform",
);
const millionaireFastlaneProps: CompositionProps = buildCompositionProps(
  millionaireFastlaneBook as unknown as BookContent,
  "longform",
);
const miracleMorningProps: CompositionProps = buildCompositionProps(
  miracleMorningBook as unknown as BookContent,
  "longform",
);
const nightCompass2025Props: CompositionProps = buildCompositionProps(
  nightCompass2025Book as unknown as BookContent,
  "longform",
);
const richDadPoorDadProps: CompositionProps = buildCompositionProps(
  richDadPoorDadBook as unknown as BookContent,
  "longform",
);
const startupDesignerProps: CompositionProps = buildCompositionProps(
  startupDesignerBook as unknown as BookContent,
  "longform",
);
const storyBrand2025Props: CompositionProps = buildCompositionProps(
  storyBrand2025Book as unknown as BookContent,
  "longform",
);
const toolsOfTitans2025Props: CompositionProps = buildCompositionProps(
  toolsOfTitans2025Book as unknown as BookContent,
  "longform",
);
// --- AUTO-GENERATED BOOKS END ---

// Build synthesized scene preview props
const synthTheme = useTheme("dark", "selfHelp");
const synthCtx: SynthesizerContext = {
  format: "longform",
  theme: synthTheme,
  from: 0,
  durationFrames: 180,
  narrationText: "",
  emotionalTones: miracleMorningFingerprint.emotionalTone,
};
const synthBlueprints = synthesizeGaps(miracleMorningGaps, synthCtx);
// Assign sequential `from` values
let synthFrom = 0;
for (const bp of synthBlueprints) {
  (bp as { from: number }).from = synthFrom;
  synthFrom += bp.durationFrames;
}
const synthProps: SynthesizedPreviewProps = {
  blueprints: synthBlueprints,
  totalDurationFrames: synthFrom,
  fps: 30,
  width: 1920,
  height: 1080,
};

// Blueprint v2 preview: hook-01 + framework-01 side by side
const blueprintV2: SceneBlueprint[] = [
  hookBlueprint as unknown as SceneBlueprint,
  {
    ...(frameworkBlueprint as unknown as SceneBlueprint),
    from: (hookBlueprint as any).durationFrames,
  },
];
const blueprintV2Props: SynthesizedPreviewProps = {
  blueprints: blueprintV2 as any,
  totalDurationFrames:
    (hookBlueprint as any).durationFrames +
    (frameworkBlueprint as any).durationFrames,
  fps: 30,
  width: 1920,
  height: 1080,
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="LongformComposition"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={LongformComposition as any}
        durationInFrames={longformProps.totalDurationFrames}
        fps={longformProps.fps}
        width={longformProps.width}
        height={longformProps.height}
        defaultProps={longformProps as any}
      />
      <Composition
        id="ShortsPreview"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={LongformComposition as any}
        durationInFrames={shortsProps.totalDurationFrames}
        fps={shortsProps.fps}
        width={shortsProps.width}
        height={shortsProps.height}
        defaultProps={shortsProps as any}
      />
      {/* --- AUTO-GENERATED COMPOSITIONS START --- */}
      <Composition
        id="BrainSuccess2025"
        component={LongformComposition as any}
        durationInFrames={brainSuccess2025Props.totalDurationFrames}
        fps={brainSuccess2025Props.fps}
        width={brainSuccess2025Props.width}
        height={brainSuccess2025Props.height}
        defaultProps={brainSuccess2025Props as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="AtomicHabits"
        component={LongformComposition as any}
        durationInFrames={atomicHabitsProps.totalDurationFrames}
        fps={atomicHabitsProps.fps}
        width={atomicHabitsProps.width}
        height={atomicHabitsProps.height}
        defaultProps={atomicHabitsProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="CrazyOneYear"
        component={LongformComposition as any}
        durationInFrames={crazyOneYearProps.totalDurationFrames}
        fps={crazyOneYearProps.fps}
        width={crazyOneYearProps.width}
        height={crazyOneYearProps.height}
        defaultProps={crazyOneYearProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="MillionaireFastlane"
        component={LongformComposition as any}
        durationInFrames={millionaireFastlaneProps.totalDurationFrames}
        fps={millionaireFastlaneProps.fps}
        width={millionaireFastlaneProps.width}
        height={millionaireFastlaneProps.height}
        defaultProps={millionaireFastlaneProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="MiracleMorning"
        component={LongformComposition as any}
        durationInFrames={miracleMorningProps.totalDurationFrames}
        fps={miracleMorningProps.fps}
        width={miracleMorningProps.width}
        height={miracleMorningProps.height}
        defaultProps={miracleMorningProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="RichDadPoorDad"
        component={LongformComposition as any}
        durationInFrames={richDadPoorDadProps.totalDurationFrames}
        fps={richDadPoorDadProps.fps}
        width={richDadPoorDadProps.width}
        height={richDadPoorDadProps.height}
        defaultProps={richDadPoorDadProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="StartupDesigner"
        component={LongformComposition as any}
        durationInFrames={startupDesignerProps.totalDurationFrames}
        fps={startupDesignerProps.fps}
        width={startupDesignerProps.width}
        height={startupDesignerProps.height}
        defaultProps={startupDesignerProps as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="StoryBrand2025"
        component={LongformComposition as any}
        durationInFrames={storyBrand2025Props.totalDurationFrames}
        fps={storyBrand2025Props.fps}
        width={storyBrand2025Props.width}
        height={storyBrand2025Props.height}
        defaultProps={storyBrand2025Props as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="NightCompass2025"
        component={LongformComposition as any}
        durationInFrames={nightCompass2025Props.totalDurationFrames}
        fps={nightCompass2025Props.fps}
        width={nightCompass2025Props.width}
        height={nightCompass2025Props.height}
        defaultProps={nightCompass2025Props as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      <Composition
        id="ToolsOfTitans2025"
        component={LongformComposition as any}
        durationInFrames={toolsOfTitans2025Props.totalDurationFrames}
        fps={toolsOfTitans2025Props.fps}
        width={toolsOfTitans2025Props.width}
        height={toolsOfTitans2025Props.height}
        defaultProps={toolsOfTitans2025Props as any}
        calculateMetadata={calculateMetadataFromManifest as any}
      />
      {/* --- AUTO-GENERATED COMPOSITIONS END --- */}
      <Composition
        id="SynthesizedPreview"
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        component={SynthesizedPreview as any}
        durationInFrames={synthProps.totalDurationFrames}
        fps={synthProps.fps}
        width={synthProps.width}
        height={synthProps.height}
        defaultProps={synthProps as any}
      />
      <Composition
        id="BlueprintV2Preview"
        component={SynthesizedPreview as any}
        durationInFrames={blueprintV2Props.totalDurationFrames}
        fps={blueprintV2Props.fps}
        width={blueprintV2Props.width}
        height={blueprintV2Props.height}
        defaultProps={blueprintV2Props as any}
      />
    </>
  );
};
